function [data] = plot_numtrials_Dec(Decisions)
% Author: James Hope, Biosensing and Biorobotics Lab, 
% Department of Mechanical Engineering, University of Minnesota
% Contact: suhasabk@umn.edu

M1 = [length(Decisions.M1D1.d);...
      length(Decisions.M1D2.d);...
      length(Decisions.M1D3.d);...
      length(Decisions.M1D4.d);...
      length(Decisions.M1D5.d);...
      length(Decisions.M1D6.d);...
      length(Decisions.M1D7.d);...
      length(Decisions.M1D8.d);...
      length(Decisions.M1D9.d);...
      length(Decisions.M1D10.d);...
      length(Decisions.M1D11.d);...
      length(Decisions.M1D12.d)];
  
M2 = [length(Decisions.M2D1.d);...
      length(Decisions.M2D2.d);...
      length(Decisions.M2D3.d);...
      length(Decisions.M2D4.d);...
      length(Decisions.M2D5.d);...
      length(Decisions.M2D6.d);...
      length(Decisions.M2D7.d);...
      length(Decisions.M2D8.d);...
      length(Decisions.M2D9.d);...
      length(Decisions.M2D10.d);...
      length(Decisions.M2D11.d);...
      length(Decisions.M2D12.d)]; 

M3 = [length(Decisions.M3D1.d);...
      length(Decisions.M3D2.d);...
      length(Decisions.M3D3.d);...
      length(Decisions.M3D4.d);...
      length(Decisions.M3D5.d);...
      length(Decisions.M3D6.d);...
      length(Decisions.M3D7.d);...
      length(Decisions.M3D8.d);...
      length(Decisions.M3D9.d)];
  
M4 = [length(Decisions.M4D1.d);...
      length(Decisions.M4D2.d);...
      length(Decisions.M4D3.d);...
      length(Decisions.M4D4.d);...
      length(Decisions.M4D5.d)]; 

M5 = [length(Decisions.M5D1.d);...
      length(Decisions.M5D2.d);...
      length(Decisions.M5D3.d);...
      length(Decisions.M5D4.d);...
      length(Decisions.M5D5.d);...
      length(Decisions.M5D6.d);...
      length(Decisions.M5D7.d);...
      length(Decisions.M5D8.d)];
  
M6 = [length(Decisions.M6D1.d);...
      length(Decisions.M6D2.d);...
      length(Decisions.M6D3.d);...
      length(Decisions.M6D4.d);...
      length(Decisions.M6D5.d);...
      length(Decisions.M6D6.d);...
      length(Decisions.M6D7.d);...
      length(Decisions.M6D8.d)];
  
M7 = [length(Decisions.M7D1.d);...
      length(Decisions.M7D2.d);...
      length(Decisions.M7D3.d);...
      length(Decisions.M7D4.d);...
      length(Decisions.M7D5.d);...
      length(Decisions.M7D6.d);...
      length(Decisions.M7D7.d)];
  
M8 = [length(Decisions.M8D1.d);...
      length(Decisions.M8D2.d);...
      length(Decisions.M8D3.d);...
      length(Decisions.M8D4.d);...
      length(Decisions.M8D5.d);...
      length(Decisions.M8D6.d);...
      length(Decisions.M8D7.d);...
      length(Decisions.M8D8.d)];
  
[data] = mean_std(M1,M2,M3,M4,M5,M6,M7,M8);

figure
hold on
plot(M1,'-','Color',[0.5 0.5 0.5])
plot(M2,'-','Color',[0.5 0.5 0.5])
plot(M3,'-','Color',[0.5 0.5 0.5])
plot(M4,'-','Color',[0.5 0.5 0.5])
plot(M5,'-','Color',[0.5 0.5 0.5])
plot(M6,'-','Color',[0.5 0.5 0.5])
plot(M7,'-','Color',[0.5 0.5 0.5])
plot(M8,'-','Color',[0.5 0.5 0.5])
plot(data(:,1),'-','Color',[0.5 0.5 0.5],'LineWidth',4)
xlabel('session')
ylabel('number of trials/session')
ylim([0 22])
xlim([0 8])
[~,~,~,~,datas,dataf] = plot_successfail_Dec(Decisions,1,0);

figure
yyaxis left
plot(data(:,5),'--','LineWidth',2)
hold on
plot(datas(:,5)+dataf(:,5),'-','LineWidth',2)
ylim([0 100])
xlabel('session')
ylabel('number of trials all mice')
yyaxis right
plot(data(:,6),'-','LineWidth',2)
ylim([0 10])
ylabel('number of mice')
legend('total number of trials','total number of decisions','number of mice')
  
xlim([0 8])

end

