% determining where to clip data
% clipping is neccessary because data saving starts begfore mouse is
% docked, and stops after mouse is undocked => forces applied by the
% operator are measured during docking/undocking

% to determine where to clip the data:
% clip(1) = when y position increases from 0 the first time (i.e. when the 
% mouse moves off the starting position). Forces before this point are
% generated by the user docking the mouse
% clip(2) = either the last point in the data array, or if docking forces
% are observable in the data, then some point before these forces begin.
% clip = [clip(1) clip(2)];

load 'Mouse276_8maze_22_3_22_v2.mat'
data = Mouse276_8maze_22_3_22_v2;

tincr = 0.01;   % (s)

figure
subplot(1,2,1)
plot(data(:,5:6));
title(' x-y-yaw position vs time')
xlabel('time (ms)')
ylabel('position (m)')

yyaxis right
plot(data(:,18));
ylabel('Xforce (N)')
legend('x','y','force')

subplot(1,2,2)
plot(data(:,5),data(:,6));
title('xy position')
xlabel('x position (m)')
ylabel('y position (m)')

%% 

