function [data] = plot_numtrials(Eightmaze)
% Author: James Hope, Biosensing and Biorobotics Lab, 
% Department of Mechanical Engineering, University of Minnesota
% Contact: suhasabk@umn.edu

M1 = [length(Eightmaze.M1D1.d);...
      length(Eightmaze.M1D2.d);...
      length(Eightmaze.M1D3.d);...
      length(Eightmaze.M1D4.d);...
      length(Eightmaze.M1D5.d);...
      length(Eightmaze.M1D6.d);...
      length(Eightmaze.M1D7.d);...
      length(Eightmaze.M1D8.d)];
  
M2 = [length(Eightmaze.M2D1.d);...
      length(Eightmaze.M2D2.d);...
      length(Eightmaze.M2D3.d);...
      length(Eightmaze.M2D4.d);...
      length(Eightmaze.M2D5.d)]; 

M3 = [length(Eightmaze.M3D1.d);...
      length(Eightmaze.M3D2.d);...
      length(Eightmaze.M3D3.d);...
      length(Eightmaze.M3D4.d);...
      length(Eightmaze.M3D5.d);...
      length(Eightmaze.M3D6.d);...
      length(Eightmaze.M3D7.d);...
      length(Eightmaze.M3D8.d)];
  
M4 = [length(Eightmaze.M4D1.d);...
      length(Eightmaze.M4D2.d);...
      length(Eightmaze.M4D3.d);...
      length(Eightmaze.M4D4.d);...
      length(Eightmaze.M4D5.d)]; 
  
M5 = [length(Eightmaze.M5D1.d);...
      length(Eightmaze.M5D2.d);...
      length(Eightmaze.M5D3.d);...
      length(Eightmaze.M5D4.d);...
      length(Eightmaze.M5D5.d)]; 
  
[data] = mean_std(M1,M2,M3,M4,M5);

figure
hold on
plot(M1,'-','Color',[0.5 0.5 0.5])
plot(M2,'-','Color',[0.5 0.5 0.5])
plot(M3,'-','Color',[0.5 0.5 0.5])
plot(M4,'-','Color',[0.5 0.5 0.5])
plot(M5,'-','Color',[0.5 0.5 0.5])
plot(data(:,1),'-','Color',[0.5 0.5 0.5],'LineWidth',4)
xlabel('session')
ylabel('number of laps/session')
  
end

