function [] = plot_forces_mice(Eightmaze)
% Author: James Hope, Biosensing and Biorobotics Lab, 
% Department of Mechanical Engineering, University of Minnesota
% Contact: suhasabk@umn.edu

% plot day 1 vs final day force distributions comparing mice

% day 1 fL = positive (left) Y forces; fR = negative (right) Y forces
x = [Eightmaze.M1D1.fL; Eightmaze.M1D1.fR;...
    Eightmaze.M2D1.fL; Eightmaze.M2D1.fR;...
    Eightmaze.M3D1.fL; Eightmaze.M3D1.fR;...
    Eightmaze.M4D1.fL; Eightmaze.M4D1.fR;...
    Eightmaze.M5D1.fL; Eightmaze.M5D1.fR];

g = [repmat({'M1L'},size(Eightmaze.M1D1.fL));...
    repmat({'M1R'},size(Eightmaze.M1D1.fR));...
    repmat({'M2L'},size(Eightmaze.M2D1.fL));...
    repmat({'M2R'},size(Eightmaze.M2D1.fR));...
    repmat({'M3L'},size(Eightmaze.M3D1.fL));...
    repmat({'M3R'},size(Eightmaze.M3D1.fR));...
    repmat({'M4L'},size(Eightmaze.M4D1.fL));...
    repmat({'M4R'},size(Eightmaze.M4D1.fR));...
    repmat({'M5L'},size(Eightmaze.M5D1.fL));...
    repmat({'M5R'},size(Eightmaze.M5D1.fR))];

subplot(2,2,1)
boxplot(x,g,'PlotStyle','compact','symbol','')
ylabel('Y forces (N)')
title('Y - day 1')
xlabel('mouse id')
ylim([-1 1])

% day 1 tL = positive (left) Yaw forces; tR = negative (right) Y forces
x = [Eightmaze.M1D1.tL; Eightmaze.M1D1.tR;...
    Eightmaze.M2D1.tL; Eightmaze.M2D1.tR;...
    Eightmaze.M3D1.tL; Eightmaze.M3D1.tR;...
    Eightmaze.M4D1.tL; Eightmaze.M4D1.tR;...
    Eightmaze.M5D1.tL; Eightmaze.M5D1.tR];

g = [repmat({'M1L'},size(Eightmaze.M1D1.tL));...
    repmat({'M1R'},size(Eightmaze.M1D1.tR));...
    repmat({'M2L'},size(Eightmaze.M2D1.tL));...
    repmat({'M2R'},size(Eightmaze.M2D1.tR));...
    repmat({'M3L'},size(Eightmaze.M3D1.tL));...
    repmat({'M3R'},size(Eightmaze.M3D1.tR));...
    repmat({'M4L'},size(Eightmaze.M4D1.tL));...
    repmat({'M4R'},size(Eightmaze.M4D1.tR));...
    repmat({'M5L'},size(Eightmaze.M5D1.tL));...
    repmat({'M5R'},size(Eightmaze.M5D1.tR))];

subplot(2,2,3)
boxplot(x,g,'PlotStyle','compact','symbol','')
ylabel('Yaw forces (Nm)')
title('Yaw - day 1')
xlabel('mouse id')
ylim([-0.02 0.02])

% day final fL = positive (left) Y forces; fR = negative (right) Y forces
x = [Eightmaze.M1D8.fL; Eightmaze.M1D8.fR;...
    Eightmaze.M2D5.fL; Eightmaze.M2D5.fR;...
    Eightmaze.M3D8.fL; Eightmaze.M3D8.fR;...
    Eightmaze.M4D5.fL; Eightmaze.M4D5.fR;...
    Eightmaze.M5D5.fL; Eightmaze.M5D5.fR];

g = [repmat({'M1L'},size(Eightmaze.M1D8.fL));...
    repmat({'M1R'},size(Eightmaze.M1D8.fR));...
    repmat({'M2L'},size(Eightmaze.M2D5.fL));...
    repmat({'M2R'},size(Eightmaze.M2D5.fR));...
    repmat({'M3L'},size(Eightmaze.M3D8.fL));...
    repmat({'M3R'},size(Eightmaze.M3D8.fR));...
    repmat({'M4L'},size(Eightmaze.M4D5.fL));...
    repmat({'M4R'},size(Eightmaze.M4D5.fR));...
    repmat({'M5L'},size(Eightmaze.M5D5.fL));...
    repmat({'M5R'},size(Eightmaze.M5D5.fR))];

subplot(2,2,2)
boxplot(x,g,'PlotStyle','compact','symbol','')
title('Y - day final')
ylabel('Y forces (N)')
xlabel('mouse id')
ylim([-1 1])

% day final tL = positive (left) Yaw forces; tR = negative (right) Y forces
x = [Eightmaze.M1D8.tL; Eightmaze.M1D8.tR;...
    Eightmaze.M2D5.tL; Eightmaze.M2D5.tR;...
    Eightmaze.M3D8.tL; Eightmaze.M3D8.tR;...
    Eightmaze.M4D5.tL; Eightmaze.M4D5.tR;...
    Eightmaze.M5D5.tL; Eightmaze.M5D5.tR];

g = [repmat({'M1L'},size(Eightmaze.M1D8.tL));...
    repmat({'M1R'},size(Eightmaze.M1D8.tR));...
    repmat({'M2L'},size(Eightmaze.M2D5.tL));...
    repmat({'M2R'},size(Eightmaze.M2D5.tR));...
    repmat({'M3L'},size(Eightmaze.M3D8.tL));...
    repmat({'M3R'},size(Eightmaze.M3D8.tR));...
    repmat({'M4L'},size(Eightmaze.M4D5.tL));...
    repmat({'M4R'},size(Eightmaze.M4D5.tR));...
    repmat({'M5L'},size(Eightmaze.M5D5.tL));...
    repmat({'M5R'},size(Eightmaze.M5D5.tR))];

subplot(2,2,4)
boxplot(x,g,'PlotStyle','compact','symbol','')
title('Yaw - day final')
ylabel('Yaw forces (Nm)')
xlabel('mouse id')
ylim([-0.02 0.02])

end

